### ISSUE TITLE
pkl file

### ISSUE THREAD

**Issue by fangyaoyu1999** [ojedaf/vCLIMB_Benchmark#1]
I would like to ask how the pkl file is generated?

**Comment by ojedaf** [comment]
For the pkl files that contain the tasks, we divide the datasets into 10 and 20 tasks without overlap. They are generated randomly, taking into account the Train, Val, and Test partitions of each dataset. It is to simulate a real scenario when you do not know when and what classes will appear. We provide all the partitions to maintain a fair comparison. I appreciate your interest :)

**Comment by fangyaoyu1999** [comment]
If so, can you send me a copy of this randomly generated code? I want to try it on other datasets like hmdb51 and ssv1

**Comment by cyoungx** [comment]
> I would like to ask how the pkl file is generated?

Perhaps the author wants you to make the pkl files for yourself?

**Comment by ojedaf** [comment]
@YeungChiu and @fangyaoyu1999, you can do the pkl files by yourself if you want. However, the idea is to have standardized tasks saved in pkl files to maintain the same scenarios for all works (Better comparison). As I mentioned, the tasks on the pkl files were randomly selected without overlap, considering all classes in the desired dataset. In what dataset do you want to work? Thank you very much for your interest in our work.
