### ISSUE TITLE
request for clarification about the benchmark

### ISSUE THREAD

**Issue by hrbust-zlz** [ojedaf/vCLIMB_Benchmark#4]
Hello, Thank you for this excellent innovation. I'm going to evaluate my video CIL solution on vCLIMB. I get that in vCLIMB there were no test data in ActivityNet, and in the souce code I found that an incremental learning model is tested on both val and test set in each dataset if available. I would like to ask that, are the video CIL results on every dataset calculated on val set? If so, could I just completely ignore the test set of UCF101 and Kinetics?

**Comment by ojedaf** [comment]
Hello @hrbust-zlz, thank you very much for your interest in our work. You are right ActivityNet does not have a test partition. It is because this partition has not been released by ActivityNet Authors. Therefore, In this dataset, we report the results of the validation set.
